networks:
  honeypotharbor-attacker-network:
    external: true
  honeypotharbor-internal-network:
    external: true

services:
  filebeat:
    image: elastic/filebeat:9.1.2
    container_name: honeypotharbor-filebeat-1
    user: root
    command: ["--strict.perms=false"]
    networks:
      honeypotharbor-attacker-network:
        ipv4_address: 192.168.1.140
      honeypotharbor-internal-network:
        ipv4_address: 192.168.1.113
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../attacker-net/logs/cowrie1:/logs/cowrie1:ro
      - ../attacker-net/logs/cowrie2:/logs/cowrie2:ro
      - ../attacker-net/logs/cowrie3:/logs/cowrie3:ro
      - ../attacker-net/logs/testlogs:/logs/testlogs:ro