filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /logs/cowrie1/cowrie.json
      - /logs/cowrie2/cowrie.json
      - /logs/cowrie3/cowrie.json
    parsers:
      - ndjson:
          keys_under_root: true
          add_error_key: true
    ignore_older: 0s

output.logstash:
  hosts: ["192.168.1.112:5044"]
#output.console:
#  pretty: true

processors:
  - add_tags:
      tags: ["cowrie", "honeypotharbor"]