spring:
  application:
    name: honeypot-harbor-backend
  datasource:
    url: jdbc:postgresql://192.168.1.101:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
        hibernate:
          format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: http://${ELASTIC_IP}:9200
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    
management:
  health:
    elasticsearch:
      enabled: false
