spring:
  application:
    name: honeypot-harbor-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: honeypot
    password: harbor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
