networks:
  honeypotharbor-internal-network:
    driver: bridge

services:
  postgres:
    image: postgres:14
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - honeypotharbor-internal-network

  elasticsearch:
    image: elasticsearch:9.1.2
    ports:
      - "9200:9200"   
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - honeypotharbor-internal-network

  logstash:
    image: logstash:9.1.2
    environment:
      - xpack.monitoring.enabled=true
      - ELASTIC_USERNAME=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    expose:
      - "5044"
    networks:
      - honeypotharbor-internal-network

  backend:
    build: ./backend
    depends_on:
      - postgres
      - elasticsearch
    expose:
      - "8080"
    networks:
      - honeypotharbor-internal-network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - honeypotharbor-internal-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"     # external access to frontend
      - "5044:5044" # external access to logstash
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - logstash
    networks:
      - honeypotharbor-internal-network

volumes:
  postgres_data:
  es_data:

#networks:
#  dockervlan:
#    name: dockervlan
#    driver: macvlan
#    driver_opts:
#      parent: wlan0
#    ipam:
#      config:
#        - subnet: "192.168.0.0/24"
#          ip_range: "192.168.0.64/26"
#          gateway: "192.168.0.1"
